(defun +meow-setup ()
  (meow-leader-define-key
   '("," . highlight-symbol-prev)
   '("." . highlight-symbol-next)
   '("k" . kill-buffer)
   '("l" . goto-line)
   '("h" . other-window)
   '("z" . +eval-and-bound-to-c-z)
   '("t" . transpose-sexps)
   '("i" . counsel-imenu)
   '("r" . sp-raise-sexp)
   '("s" . sp-split-sexp)
   '("u" . sp-splice-sexp)
   '("n" . dumb-jump-go)
   '("j" . sp-join-sexp)
   '("(" . sp-wrap-round)
   '("[" . sp-wrap-square)
   '("{" . sp-wrap-curly)
   '("o" . delete-other-windows)
   '("-" . split-window-below)
   '("/" . swiper)
   '("\\" . split-window-right)
   '("'" . paredit-meta-doublequote)
   '("#" . deft)
   '("m" . magit-status)
   '("b" . magit-blame)
   '("p" . projectile-find-file)
   '("b" . counsel-switch-buffer)
   '("g" . projectile-ripgrep)
   '("f" . find-file)
   '("F" . find-file-literally)))

(use-package meow
  :quelpa
  (meow :repo "DogLooksGood/meow" :fetcher github)
  :config
  (+meow-setup)
  (meow-global-mode 1))

(provide 'init-meow)
