;;; -*- lexical-binding: t -*-

(deftheme joker "Minimal colortheme for terminal.")

(defvar joker--bg nil)

(if (display-graphic-p)
    (setq joker--bg "#171717")
  (setq joker--bg nil))

(custom-theme-set-faces
 'joker
 `(default                        ((t (:foreground "#a8a8a8" :background ,joker--bg))))
 '(mc/cursor-face                 ((t (:background "#949494" :foreground "black"))))
 '(region                         ((t (:background "#004D2A"))))
 '(hl-line                        ((t (:background "#202020"))))
 '(show-paren-match               ((t (:underline "#00AF5F"))))
 '(company-tooltip-common         ((t (:foreground "#D7005F"))))
 '(company-tooltip-common-selection ((t (:foreground "black"))))
 '(company-tooltip                ((t (:background "black"))))
 '(company-tooltip-selection      ((t (:background "#D7AF00" :foreground "black"))))
 '(company-scrollbar-bg           ((t (:background "#303030"))))
 '(company-scrollbar-fg           ((t (:background "#4E4E4E"))))
 '(font-lock-comment-face         ((t (:foreground "#00AFAF"))))
 '(font-lock-string-face          ((t (:foreground "#E01717"))))
 '(font-lock-doc-face             ((t (:foreground "#00AFAF"))))
 '(font-lock-builtin-face         ((t ())))
 '(font-lock-type-face            ((t ())))
 '(font-lock-variable-name-face   ((t ())))
 '(font-lock-keyword-face         ((t ())))
 '(font-lock-constant-face        ((t (:foreground "#D7AF00"))))
 '(font-lock-function-name-face   ((t (:foreground "#00AFD7"))))
 '(font-lock-warning-face         ((t (:foreground "yellow"))))
 '(m4d-insert-indicator           ((t (:foreground "#D7AF00"))))
 '(m4d-visual-indicator           ((t (:foreground "#00D787"))))
 '(cider-result-overlay-face      ((t (:background "#000087"))))
 '(mode-line                      ((t ())))
 '(clojure-character-face         ((t (:inherit font-lock-constant-face))))
 '(highlight                      ((t (:background "#00AFAF" :foreground "black"))))
 '(isearch                        ((t (:background "#00D75F" :foreground "black"))))
 '(isearch-fail                   ((t (:backgronud "#D75FFF" :foreground "#606060"))))
 '(popup-isearch-match            ((t (:background "#D7AF00" :foreground "black"))))
 '(ivy-highlight-face             ((t (:backgronud "#00AFFF" :foreground "black"))))
 '(ivy-yanked-word                ((t (:background "yellow" :foreground "black"))))
 '(ivy-remote                     ((t ())))
 '(vertical-border                ((t (:background nil :foreground "black"))))
 '(counsel-outline-default        ((t ())))
 '(completions-common-part        ((t ())))
 '(minibuffer-prompt              ((t ())))
 '(lazy-highlight                 ((t (:foreground "white"))))
 '(magit-diff-file-heading-highlight ((t (:background "#000087"))))
 '(magit-section-highlight           ((t (:background "#000087"))))
 '(swiper-background-match-face-1 ((t (:background "#00D75F" :foreground "black"))))
 '(swiper-background-match-face-2 ((t (:background "#00D75F" :foreground "black"))))
 '(swiper-background-match-face-3 ((t (:background "#00D75F" :foreground "black"))))
 '(swiper-background-match-face-4 ((t (:background "#00D75F" :foreground "black"))))
 '(solaire-default-face           ((t (:background "#262626"))))
 '(swiper-match-face-1            ((t (:foreground "white"))))
 '(swiper-match-face-2            ((t (:foreground "white"))))
 '(swiper-match-face-3            ((t (:foreground "white"))))
 '(swiper-match-face-4            ((t (:foreground "white"))))
 '(ivy-current-match              ((t (:background "#D7AF00" :foreground "black"))))
 '(ivy-minibuffer-match-highlight ((t (:foreground "#00D7D7"))))
 '(ivy-minibuffer-match-face-1    ((t (:foreground "#9E9E9E"))))
 '(ivy-minibuffer-match-face-2    ((t (:foreground "#D7005F"))))
 '(ivy-minibuffer-match-face-3    ((t (:foreground "#D7AF00"))))
 '(ivy-minibuffer-match-face-4    ((t (:foreground "#00FFD7"))))
 '(yas-field-highlight-face       ((t (:background "#00D787" :foreground "black"))))
 '(org-document-title             ((t (:inherit font-lock-string-face))))
 '(line-number-current-line       ((t (:foreground "#D7AF00")))))

(and load-file-name
     (boundp 'custom-theme-load-path)
     (add-to-list 'custom-theme-load-path
                  (file-name-as-directory
                   (file-name-directory load-file-name))))


(provide-theme 'joker)
