;;; -*- lexical-binding: t -*-

(deftheme joker-light "A simple medium contrast light theme.")

(let ((bg+1 "#fffdb8")
      (bg-1 "#e3e1b3"))
  (custom-theme-set-faces
   'joker-light
   '(default                        ((t (:background "#fcfcf2"  :foreground "#000000"))))
   '(cursor                         ((t (:background "black"))))
   '(region                         ((t (:background "#f5ea9a"))))
   '(highlight-symbol-face          ((t ())))
   `(hl-line                        ((t ())))
   '(yascroll:thumb-fringe          ((t (:background "#d4bbfa" :foreground "#d4bbfa"))))
   '(yascroll:thumb-text-area       ((t (:background "#d4bbfa" :foreground "#d4bbfa"))))
   '(fringe                         ((t (:background nil))))
   '(window-divider                 ((t (:foreground "#CCCCCC"))))
   '(show-paren-match               ((t (:underline "#257d22"))))
   '(company-tooltip-common         ((t (:inherit font-lock-comment-face))))
   '(company-tooltip-common-selection ((t (:inherit font-lock-constant-face :inverse-video t))))
   `(company-tooltip                ((t (:background "#e1ffdb"))))
   '(company-tooltip-selection      ((t (:inherit font-lock-constant-face :inverse-video t))))
   `(company-scrollbar-bg           ((t (:background ,bg-1))))
   `(company-scrollbar-fg           ((t (:background ,bg+1))))
   '(font-lock-comment-face         ((t (:background "#daf7eb" :extend t))))
   '(font-lock-string-face          ((t (:background "#fff0f0"))))
   '(font-lock-doc-face             ((t (:background "#daf7eb" :extend t))))
   '(font-lock-builtin-face         ((t ())))
   '(font-lock-type-face            ((t ())))
   '(font-lock-variable-name-face   ((t ())))
   '(font-lock-keyword-face         ((t ())))
   '(font-lock-constant-face        ((t (:background "#f8f0ff"))))
   '(font-lock-function-name-face   ((t (:background "#e8fbff"))))
   '(font-lock-warning-face         ((t (:background "#FAFA88"))))
   '(meow-keypad-indicator           ((t (:foreground "#ab3007"))))
   '(meow-insert-indicator           ((t (:foreground "#257d22"))))
   '(meow-normal-indicator           ((t (:foreground "#713da6"))))
   '(meow-motion-indicator           ((t (:foreground "#1853cc"))))
   '(meow-keypad-cursor             ((t (:background "#ab3007"))))
   '(meow-insert-cursor             ((t (:background "#257d22"))))
   '(meow-normal-cursor             ((t (:background "#713da6"))))
   '(meow-motion-cursor             ((t (:background "#1853cc"))))
   '(cider-result-overlay-face      ((t (:background "yellow"))))
   '(mode-line                      ((t (:background "yellow"))))
   '(mode-line-inactive             ((t (:background "yellow"))))
   '(clojure-character-face         ((t (:inherit font-lock-constant-face))))
   '(highlight                      ((t (:underline "#00BBBB"))))
   '(isearch                        ((t (:background "#009F2F" :foreground "black"))))
   '(isearch-fail                   ((t (:backgronud "#D75FFF" :foreground "black"))))
   '(popup-isearch-match            ((t (:background "#CFA300" :foreground "black"))))
   '(ivy-highlight-face             ((t ())))
   '(ivy-yanked-word                ((t (:background "#a33817" :foreground "black"))))
   '(ivy-remote                     ((t ())))
   '(vertical-border                ((t (:background nil :foreground "black"))))
   '(counsel-outline-default        ((t ())))
   '(completions-common-part        ((t ())))
   '(minibuffer-prompt              ((t ())))
   '(lazy-highlight                 ((t (:foreground "#ffafa6"))))
   `(magit-diff-file-heading-highlight ((t ())))
   `(magit-section-highlight           ((t ())))
   '(magit-diff-removed             ((t (:inherit font-lock-string-face))))
   '(magit-diff-added               ((t (:inherit font-lock-comment-face))))
   `(magit-diff-removed-highlight   ((t (:inherit font-lock-string-face))))
   `(magit-diff-added-highlight     ((t (:inherit font-lock-comment-face))))
   `(magit-diff-highlight           ((t (:background ,bg+1))))
   `(magit-diff-context-highlight   ((t (:background ,bg+1))))
   '(swiper-background-match-face-1 ((t (:inherit hl-line))))
   '(swiper-background-match-face-2 ((t (:inherit hl-line))))
   '(swiper-background-match-face-3 ((t (:inherit hl-line))))
   '(swiper-background-match-face-4 ((t (:inherit hl-line))))
   '(compilation-info               ((t (:inherit font-lock-function-name-face))))
   '(match                          ((t (:inherit font-lock-doc-face))))
   '(swiper-match-face-1            ((t (:foreground "red"))))
   '(swiper-match-face-2            ((t (:foreground "red"))))
   '(swiper-match-face-3            ((t (:foreground "red"))))
   '(swiper-match-face-4            ((t (:foreground "red"))))
   '(ivy-current-match              ((t (:inverse-video t))))
   '(ivy-minibuffer-match-highlight ((t (:foreground "#00D7D7"))))
   '(ivy-minibuffer-match-face-1    ((t ())))
   '(ivy-minibuffer-match-face-2    ((t ())))
   '(ivy-minibuffer-match-face-3    ((t ())))
   '(ivy-minibuffer-match-face-4    ((t ())))
   '(yas-field-highlight-face       ((t (:box "red"))))
   '(company-template-field         ((t (:inherit yas-field-highlight-face))))
   '(org-document-title             ((t (:inherit font-lock-string-face))))
   '(org-code                       ((t (:inherit font-lock-constant-face))))
   '(line-number-current-line       ((t (:foreground "#D7AF00"))))
   '(parenthesis                    ((t (:foreground "#606060"))))
   '(popup-tip-face                 ((t (:background "#00D7D7" :foreground "black"))))
   '(telega-msg-heading             ((t (:inherit hl-line))))
   '(telega-unmuted-count           ((t (:inherit font-lock-function-name-face))))
   '(rime-preedit-face              ((t (:inverse-video nil :underline t))))
   '(rime-cursor-face               ((t (:inherit font-lock-constant-face))))
   '(rime-candidate-num-face        ((t ())))
   '(rime-comment-face              ((t ())))
   '(rime-indicator-face            ((t (:foreground "#713da6"))))
   '(rime-default-face              ((t (:background "#FEFEE0"))))
   '(dired-directory                ((t (:bold t))))
   '(slack-message-mention-face     ((t (:inherit font-lock-warning-face))))))

(and load-file-name
     (boundp 'custom-theme-load-path)
     (add-to-list 'custom-theme-load-path
                  (file-name-as-directory
                   (file-name-directory load-file-name))))

(provide-theme 'joker-light)

;;; joker-theme.el ends here
