;;; -*- lexical-binding: t -*-

(deftheme storybook "A simple medium contrast light theme.")

(defvar storybook-use-italic t
  "Non-nil means use italic for comment and docstring.")

(defvar storybook-header-scales '(2.2 1.8 1.6 1.4 1.2 1.2 1.2)
  "Scales for headers.")

(let ((fg "#442C09")
      (fg+1 "#806040")
      (hl "#dca485")
      (bg "#f9f9e3")
      (bg-1 "#eaeac7")
      (bg-2 "#ddddb1")
      (err "#8E1316")
      (green-bg "#e6efd2")
      (green-fg "#0A3A45")
      (red-bg "#e8dcb5")
      (gray-bg "#bdbd95")
      (red-fg "#5E1477")
      (hl2 "#cbd8b6")
      (sec-sel "#CABAE0"))
  (custom-theme-set-faces
   `storybook
   `(default                        ((((type tty)) :background ,bg)
                                     (((type graphic)) :background ,bg :foreground ,fg)))
   `(hl-line                        ((((type graphic)) :overline ,hl :underline ,hl)
                                     (((type tty)) :background "#ffffff")))
   `(cursor                         ((t (:background "black"))))
   `(region                         ((t (:background ,hl))))
   `(fringe                         ((t ())))
   `(fill-column-indicator          ((t (:foreground ,bg-1))))
   `(font-lock-comment-delimiter-face ((t (:background ,green-bg :foreground ,fg+1 :italic t))))
   `(font-lock-comment-face         ((t (:background ,green-bg :extend t :italic t))))
   `(font-lock-doc-face             ((t (:background ,green-bg :extend t :italic t))))
   `(font-lock-warning-face         ((t (:foreground ,err))))
   `(font-lock-string-face          ((t (:background ,red-bg))))
   `(font-lock-function-name-face   ((t (:background ,bg-1))))
   `(font-lock-keyword-face         ((t (:foreground ,green-fg))))
   `(font-lock-constant-face        ((t (:foreground ,red-fg))))
   `(font-lock-builtin-face         ((t ())))
   `(font-lock-variable-name-face   ((t ())))
   `(font-lock-type-face            ((t ())))
   `(font-lock-preprocessor-face    ((t (:inherit font-lock-constant-face))))
   `(compilation-warning            ((t (:inherit font-lock-warning-face))))
   `(warning                        ((t (:inherit font-lock-warning-face))))

   ;; Company
   `(company-tooltip-common         ((t ())))
   `(company-tooltip-common-selection ((t (:bold t))))
   `(company-tooltip                ((t (:background ,bg-2))))
   `(company-tooltip-search         ((t ())))
   `(company-tooltip-selection      ((t (:inverse-video t))))
   `(company-tooltip-annotation     ((t ())))
   `(company-scrollbar-bg           ((t (:background ,bg))))
   `(company-scrollbar-fg           ((t (:background ,fg))))
   `(company-template-field         ((t (:inherit yas-field-highlight-face))))

   `(meow-keypad-indicator          ((t ())))
   `(meow-insert-indicator          ((t ())))
   `(meow-normal-indicator          ((t ())))
   `(meow-motion-indicator          ((t ())))
   `(meow-keypad-cursor             ((t ())))
   `(meow-insert-cursor             ((t ())))
   `(meow-normal-cursor             ((t ())))
   `(meow-motion-cursor             ((t ())))

   ;; Diff-hl
   `(diff-hl-insert                 ((t (:foreground ,green-bg :background ,green-bg))))
   `(diff-hl-change                 ((t (:foreground ,gray-bg :background ,gray-bg))))
   `(diff-hl-delete                 ((t (:foreground ,red-bg :background ,red-bg))))

   ;; Magit
   ;; `(magit-diff-file-heading-highlight ((t (:background ,bg+1))))
   `(magit-branch-current              ((t (:box t :background ,bg-2))))
   `(magit-branch-local                ((t (:background ,bg-1))))
   `(magit-branch-remote               ((t (:background ,bg-2))))
   `(magit-branch-remote-head          ((t (:box t :background ,bg-2))))
   `(magit-header-line                 ((t (:bold t))))
   `(magit-head                        ((t ())))
   `(magit-section-highlight           ((t (:background ,bg-1))))
   `(magit-section-heading             ((t (:bold t))))
   `(magit-section-selection           ((t (:bold t))))
   `(magit-diff-hunk-heading-highlight ((t (:inverse-video t))))
   `(magit-diff-hunk-heading ((t (:foreground ,bg-1))))
   `(magit-diff-removed             ((t ())))
   `(magit-diff-added               ((t ())))
   `(magit-diff-removed-highlight   ((t (:background ,red-bg))))
   `(magit-diff-added-highlight     ((t (:background ,green-bg))))
   `(magit-diff-highlight           ((t ())))
   `(magit-diff-context-highlight   ((t ())))

   `(dired-directory                ((t (:inherit font-lock-keyword-face))))
   `(mode-line                      ((((type tty))
                                      (:background "grey70"))
                                     (((type graphic))
                                      (:box (:line-width (-1 . -1) :color ,fg) :background ,bg-2))))
   `(mode-line-inactive             ((((type tty))
                                      (:background "grey80"))
                                     (((type graphic))
                                      (:box (:line-width (-1 . -1) :color ,fg) :background ,bg-1))))
   `(parenthesis                    ((t ())))
   `(highlight-symbol-face          ((t ())))
   `(yascroll:thumb-fringe          ((t (:background "#606060" :foreground "#606060"))))
   `(yascroll:thumb-text-area       ((t (:background "#606060" :foreground "#606060"))))
   `(rime-indicator-face            ((t (:foreground "#1853cc"))))
   `(rime-indicator-dim-face        ((t ())))
   `(rime-default-face              ((t (:foreground "#303030"))))
   `(rime-preedit-face              ((t (:inverse-video nil :underline t))))
   `(rime-cursor-face               ((t (:inherit font-lock-constant-face))))
   `(rime-candidate-num-face        ((t ())))
   `(rime-highlight-candidate-face  ((t (:background "#ede4d1"))))
   `(rime-comment-face              ((t ())))
   `(telega-msg-heading             ((t (:background ,bg-1))))
   `(telega-entity-type-code        ((t (:inherit fixed-pitch))))
   `(telega-entity-type-pre         ((t (:inherit fixed-pitch))))
   `(cider-fringe-good-face         ((t (:foreground "#006666"))))
   `(web-mode-html-attr-name-face   ((t ())))
   `(web-mode-html-tag-face         ((t ())))
   `(line-number                    ((t :foreground ,fg+1)))
   `(line-number-current-line       ((((type graphic))
                                      :overline ,hl
                                      :underline ,hl)))
   `(mc/cursor-bar-face             ((t (:background "grey50" :height 1))))
   `(dired-subtree-depth-1-face     ((t (:background "grey90"))))
   `(dired-subtree-depth-2-face     ((t (:background "grey80"))))
   `(dired-subtree-depth-3-face     ((t (:background "grey70"))))
   `(dired-subtree-depth-4-face     ((t (:background "grey90"))))
   `(dired-subtree-depth-5-face     ((t (:background "grey80"))))
   `(dired-subtree-depth-6-face     ((t (:background "grey70"))))
   `(isearch                        ((t (:background "#ff99a5"))))
   `(ivy-current-match              ((t (:background "#EAC5A0"))))
   `(ivy-minibuffer-match-highlight ((t (:foreground "#00D7D7"))))
   `(ivy-minibuffer-match-face-1    ((t ())))
   `(ivy-minibuffer-match-face-2    ((t ())))
   `(ivy-minibuffer-match-face-3    ((t ())))
   `(ivy-minibuffer-match-face-4    ((t ())))
   `(minibuffer-prompt              ((t (:foreground "#0a3a45"))))
   `(web-mode-function-call-face    ((t ())))
   `(web-mode-function-name-face    ((t ())))
   `(web-mode-html-tag-face         ((t (:bold t))))
   `(window-divider                 ((t (:foreground "grey60"))))
   `(vertical-border                ((t (:foreground "grey20"))))
   `(web-mode-html-tag-bracket-face ((t (:inherit parenthesis))))
   `(web-mode-doctype-face          ((t (:foreground "grey40"))))
   `(web-mode-symbol-face           ((t (:inherit font-lock-constant-face))))
   `(css-selector                   ((t (:inherit font-lock-constant-face))))
   `(markdown-header-face-1         ((t (:bold t :height 2.2))))
   `(markdown-header-face-2         ((t (:bold t :height 1.8))))
   `(markdown-header-face-3         ((t (:bold t :height 1.4))))
   `(markdown-header-face-4         ((t (:bold t :height 1.2))))
   `(markdown-header-face-5         ((t (:bold t :height 1.2))))
   `(markdown-header-face-6         ((t (:bold t :height 1.2))))
   `(markdown-header-face-7         ((t (:bold t :height 1.2))))
   `(org-document-title  ((t (:foreground ,fg :height 2.2))))
   `(org-headline-done   ((t (:inherit shadow))))
   `(org-block           ((t (:background "#f2ecd7" :extend t))))
   `(org-meta-line       ((t (:background "#e5dfc9" :extend t))))
   `(org-table           ((t (:foreground "grey40"))))
   `(org-level-1         ((t (:bold t :height 2.2))))
   `(org-level-2         ((t (:bold t :height 1.8))))
   `(org-level-3         ((t (:bold t :height 1.4))))
   `(org-level-4         ((t (:bold t :height 1.2))))
   `(org-level-5         ((t (:bold t :height 1.2))))
   `(org-level-6         ((t (:bold t :height 1.2))))
   `(org-level-7         ((t (:bold t :height 1.2))))
   `(colorful-paren-round ((t (:foreground ,fg+1))))
   `(secondary-selection ((t (:background ,sec-sel))))
   `(header-line         ((t (:background "#ede4d1" :foreground "#442c09" :underline "#a8a296"))))
   `(help-key-binding    ((t (:background ,bg-2))))
   `(selectrum-current-candidate    ((t (:background ,bg-2))))
   `(selectrum-prescient-primary-highlight ((t (:underline t))))
   ;; colorful paren
   `(colorful-round           ((t (:foreground ,fg+1))))
   `(colorful-square          ((t (:foreground ,green-fg))))
   `(colorful-curly           ((t (:foreground ,red-fg))))
   `(colorful-semicolon       ((t (:foreground ,green-fg))))

   `(tab-bar                        ((t ())))
   `(tab-bar-tab-group-current      ((t ())))
   `(tab-bar-tab                    ((t (:inherit mode-line))))
   `(tab-bar-tab-group-inactive     ((t ())))
   `(tab-bar-tab-inactive           ((t (:inherit shadow))))))

(and load-file-name
     (boundp 'custom-theme-load-path)
     (add-to-list 'custom-theme-load-path
                  (file-name-as-directory
                   (file-name-directory load-file-name))))

(provide-theme 'storybook)
;;; storybook-theme.el ends here
